#!/bin/env python

import requests
import json
import hashlib
import base64
import time
import hmac

#Account Info
AccessId ='48v2wRzfK94y53sq5EuF'
AccessKey ='H_D9i(f5B^U36^K6i42=^nSe75gy382Bf6{)P+'
Company = 'api'

#Request Info
httpVerb ='GET'
queryParams = '?start=1478296606&end=1478297686'
data = ''

#Construct URL
deviceCount = 3000
if deviceCount <= 3000:
resourcePath = '/device/devices/533/devicedatasources/10256/data'
else:
resourcePath = '/device/devices/533/devicedatasources/10256/data/?useLocal=true'

url = 'https://'+ Company +'.logicmonitor.com/santaba/rest' + resourcePath + queryParams

#Get current time in milliseconds
epoch = str(int(time.time() * 1000))

#Concatenate Request details
requestVars = httpVerb + epoch + data + resourcePath

#Construct signature
hmac1 = hmac.new(AccessKey.encode(),msg=requestVars.encode(),digestmod=hashlib.sha256).hexdigest()
signature = base64.b64encode(hmac1.encode())

#Construct headers
auth = 'LMv1 ' + AccessId + ':' + signature.decode() + ':' + epoch
headers = {'Content-Type':'application/json','Authorization':auth}

#Make request
response = requests.get(url, data=data, headers=headers)

#Print status and body of response
print('Response Status:',response.status_code)
print('Response Body:',response.content)
